include:
  # -----------------------------------------
  # Your other keyboard parts here
  # -----------------------------------------
  # Change the board appropriately, you can use any board
  - board: nice_nano_v2
    shield: corne_dongle dongle_display
    artifact-name: corne_dongle_nice_nano_v2
    
  # Add these cmake-args to the peripherals you wish to use with the dongle
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left_nice_nano_v2
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_right_nice_nano_v2

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_nice_nano_v2